name: check feeds
on:
  workflow_dispatch:
jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - continue-on-error: true
        run: |
          wget --progress=dot -m -i url.in.txt
          git config --global user.email "fetch"
          git config --global user.name "fetch"
          git add .
          git commit -m "commit by fetch"
          git push origin main
