name: feeds
on:
  schedule:
    - cron: '5 */2 * * *'
  workflow_dispatch:
jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TZ=JST-9
          mkdir work0
          cd work0
          git config --global user.email "fetch"
          git config --global user.name "fetch"
          git clone --depth 1 https://x:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY .
          set +e
          wget --progress=dot --no-if-modified-since -m -i url.in.txt 2>wget.2.out < /dev/null
          wget --progress=dot -r -i url.in.2.txt 2>>wget.2.out
          wget --progress=dot --no-if-modified-since -U Mozilla -m -i url.in.3.txt 2>>wget.2.out
          mkdir generated
          wget --progress=dot -O - https://dengekionline.com/ 2>>wget.2.out | gawk -f dengekionline.com.awk > generated/dengekionline.xml
          wget --progress=dot -O - http://weathernews.jp/s/topics/json/list_s.json 2>>wget.2.out | gawk -f weathernews-j.awk > generated/weathernews.jp.lists_s.xml
          wget -S --method=HEAD https://aka.ms/vs/16/release/channel  2>&1 | gawk -f aka-ms.awk "http://aka.ms/vs/16/release/channel" "Visual Studio 2019 (c) Microsoft" > generated/aka-ms-vs-16-release-channel.xml
          set -e
          git add .
          git commit -m "commit by fetch"
          git push origin main
