name: feeds
on:
  schedule:
    - cron: '5 */2 * * *'
  workflow_dispatch:
jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "fetch"
          git config --global user.name "fetch"
          git clone --depth 1 https://x:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
          cd 69EE9759-2B44-406f-B695-977C70DC31E6
          wget --progress=dot --no-if-modified-since -m -i url.in.txt 2>wget.2.out
          git add .
          git commit -m "commit by fetch"
          git push origin main
