name: check feeds
on:
  workflow_dispatch:
jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - continue-on-error: true
        run: |
          wget -m -i url.in.txt
      - run: |
          git add .
          git commit -m "commit by workflow_dispatch"
