name: check feeds
on:
  workflow_dispatch:
jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget -m -i url.in.txt
          git add .
