name: feeds
on:
  schedule:
    - cron: '5 */2 * * *'
  workflow_dispatch:
jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TZ=JST-9
          mkdir work0
          cd work0
          git config --global user.email "fetch"
          git config --global user.name "fetch"
          git clone --depth 1 https://x:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY .
          set +e
          wget --progress=dot --no-if-modified-since -m -i url.in.txt 2>wget.2.out
          wget --progress=dot -r -i url.in.2.txt 2>>wget.2.out
          set -e
          git add .
          git commit -m "commit by fetch"
          git push origin main
