name: lslrlist
on:
  workflow_dispatch:
jobs:
  job0:
    name: lslrlist
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: ls -alR / > ls-lr.txt
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: lslr
          path: ls-lr.txt
