name: lslrlist
on:
  workflow_dispatch:
jobs:
  job0:
    name: lslrlist
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - run: |
          set +e
          ls -alR / > ls-lr.txt 2>ls-lr.e.txt
          set -e
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: lslr
          path: ls-lr.txt ls-lr.e.txt
